#!/usr/bin/env node
// Generates docs/schema-map.md: an index from every database object to the
// migrations that touch it.
//
// This is a MAP, not a schema definition. Migrations are append-only history
// and the live schema is the result of replaying them, so reconstructing
// column-level state here would produce something subtly wrong and more
// trusted than it deserves. What this answers is the question that actually
// costs time: "which of the 75 files do I open to find X?"
//
// Regenerate with `npm run docs:schema`.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const MIGRATIONS_DIR = 'supabase/migrations';
const OUT = 'docs/schema-map.md';

const strip = (name) => name.replace(/^public\./i, '').replace(/["`]/g, '');

// One entry per (object, migration) pair, tagged with what happened.
const patterns = [
  { kind: 'table', verb: 'creates', re: /create\s+table\s+(?:if\s+not\s+exists\s+)?([\w".]+)/gi },
  { kind: 'table', verb: 'alters', re: /alter\s+table\s+(?:if\s+exists\s+)?(?:only\s+)?([\w".]+)/gi },
  { kind: 'table', verb: 'drops', re: /drop\s+table\s+(?:if\s+exists\s+)?([\w".]+)/gi },
  { kind: 'function', verb: 'defines', re: /create\s+(?:or\s+replace\s+)?function\s+([\w".]+)/gi },
  { kind: 'function', verb: 'drops', re: /drop\s+function\s+(?:if\s+exists\s+)?([\w".]+)/gi },
  // Grants matter on their own: a function can be defined in one migration and
  // have its callers changed in another, which is where permission regressions
  // hide. Tracked separately so those migrations are findable.
  { kind: 'function', verb: 'grants on', re: /grant\s+[\w\s,]+?\s+on\s+function\s+([\w".]+)/gi },
  { kind: 'function', verb: 'revokes on', re: /revoke\s+[\w\s,]+?\s+on\s+function\s+([\w".]+)/gi },
  { kind: 'trigger', verb: 'defines', re: /create\s+(?:or\s+replace\s+)?trigger\s+([\w".]+)/gi },
  { kind: 'policy', verb: 'defines', re: /create\s+policy\s+"?([^"\n]+?)"?\s+on/gi },
  { kind: 'index', verb: 'defines', re: /create\s+(?:unique\s+)?index\s+(?:concurrently\s+)?(?:if\s+not\s+exists\s+)?([\w".]+)/gi },
];

const files = readdirSync(MIGRATIONS_DIR)
  .filter((f) => f.endsWith('.sql'))
  .sort();

// kind -> object name -> [{ file, verb }]
const index = new Map();

for (const file of files) {
  // Comments would otherwise register phantom references.
  const sql = readFileSync(join(MIGRATIONS_DIR, file), 'utf8')
    .replace(/--[^\n]*/g, '')
    .replace(/\/\*[\s\S]*?\*\//g, '');

  for (const { kind, verb, re } of patterns) {
    for (const match of sql.matchAll(re)) {
      const name = strip(match[1]).trim();
      if (!name) continue;

      if (!index.has(kind)) index.set(kind, new Map());
      const byName = index.get(kind);
      if (!byName.has(name)) byName.set(name, []);

      const hits = byName.get(name);
      // One line per migration per verb, however many statements it contains.
      if (!hits.some((h) => h.file === file && h.verb === verb)) {
        hits.push({ file, verb });
      }
    }
  }
}

const section = (kind, title, note) => {
  const byName = index.get(kind);
  if (!byName || byName.size === 0) return '';

  const names = [...byName.keys()].sort();
  let out = `\n## ${title}\n\n${note}\n\n`;

  for (const name of names) {
    const hits = byName.get(name);
    const created = hits.find((h) => h.verb === 'creates' || h.verb === 'defines');
    const lifecycle = hits.filter((h) => h.verb === 'drops' || h.verb === 'creates' || h.verb === 'defines');
    const dropped = lifecycle.length > 0 && lifecycle[lifecycle.length - 1].verb === 'drops';
    out += `### \`${name}\`${dropped ? ' — dropped' : ''}\n\n`;
    if (dropped) {
      out += `Removed by \`${lifecycle[lifecycle.length - 1].file}\`; listed so the name is findable.\n\n`;
    } else if (created) {
      out += `First defined in \`${created.file}\`.\n\n`;
    }
    for (const hit of hits) {
      out += `- ${hit.verb} — \`${hit.file}\`\n`;
    }
    out += '\n';
  }

  return out;
};

const PLURAL = {
  table: 'tables',
  function: 'functions',
  trigger: 'triggers',
  policy: 'policies',
  index: 'indexes',
};

const counts = [...index.entries()]
  .map(([kind, byName]) => {
    if (byName.size === 1) return `1 ${kind}`;

    return `${byName.size} ${PLURAL[kind]}`;
  })
  .join(', ');

let doc = `# Schema map

<!-- GENERATED by scripts/generateSchemaMap.mjs — do not hand-edit.
     Regenerate with \`npm run docs:schema\`. -->

An index from each database object to the migrations that touch it, built by
scanning \`${MIGRATIONS_DIR}\`. Covers ${files.length} migrations: ${counts}.

This is a **map, not a schema definition**. Migrations are append-only history
and the live schema is what you get by replaying them, so nothing here states
a table's current columns — it states where to look. For the current shape of
the database, query it (\`supabase migration list --linked\` shows what is
applied); for how the tables relate, see \`docs/architecture.md\`.
`;

doc += section(
  'table',
  'Tables',
  'Every table is RLS-protected and owner-scoped (see `docs/architecture.md`).',
);
doc += section(
  'function',
  'Functions',
  'Includes the recurring-expense generator and the balance recompute triggers.',
);
doc += section('trigger', 'Triggers', 'Row-level automation.');
doc += section('index', 'Indexes', '');
doc += section('policy', 'Policies', 'Row-level security.');

writeFileSync(OUT, doc);
console.log(`Wrote ${OUT} — ${files.length} migrations, ${counts}.`);
